#! /bin/sh

# install redis based on platform
# @author Winston Koh
# @since 1.0

REDIS_VERSION=redis-2.6.13
REDIS_ZIP_NAME="$REDIS_VERSION.tar.gz"
REDIS_HOME=$(pwd)
REDIS_HOME="$REDIS_HOME/.."
REDIS_ZIP_PATH="$REDIS_HOME/dist/$REDIS_ZIP_NAME"
REDIS_BIN="$REDIS_HOME/bin"

if [[ ! -f $REDIS_ZIP_PATH ]]; then
  echo "Corrupted redis zip. $REDIS_ZIP_PATH not found."
  exit
fi

# find out platform info
unameinfo=$(uname -a)
platforminfo=""
platformunsupported="false"

if [[ $unameinfo == Darwin* ]]; then
  platforminfo="mac64"
  echo "$platforminfo platform detected."
  if [[ $platformunsupported == "false" ]]; then
    cd $REDIS_HOME && tar xzf $REDIS_ZIP_PATH
    if [[ ! -d $REDIS_VERSION ]]; then
      echo "Corrupted redis zip. $REDIS_VERSION not found."
      exit
    fi
    cd $REDIS_VERSION
    make
  fi
elif [[ $unameinfo == Linux*_64* ]]; then
  if [[ -f /etc/redhat-release ]]; then
    platforminfo="rh64"
    echo "$platforminfo platform detected."
    elif [[ -f /etc/centos-release ]]; then
      platforminfo="cent64"
      echo "$platforminfo platform detected."
    elif [[ -f /etc/debian_version ]]; then
      platforminfo="ubuntu64"
      echo "$platforminfo platform detected."
    else
      echo "Unsupported Linux 64 bit platform."
      platformunsupported="true"
    fi
    if [[ $platformunsupported == "false" ]]; then
      cd $REDIS_HOME && tar xzf $REDIS_ZIPNAME
      if [[ ! -d $REDIS_VERSION ]]; then
        echo "Corrupted redis zip. $REDIS_VERSION not found."
        exit
      fi
      cd $REDIS_VERSION
      make
    fi
elif [[ $unameinfo == Linux* ]]; then
  if [[ -f /etc/redhat-release ]]; then
    platforminfo="rh32"
    echo "$platforminfo platform detected."
  elif [[ -f /etc/centos-release ]]; then
    platforminfo="cent32"
    echo "$platforminfo platform detected."
  elif [[ -f /etc/debian_version ]]; then
    platforminfo="ubuntu32"
    echo "$platforminfo platform detected."
  else
    echo "Unsupported Linux 32 bit platform."
    platformunsupported="true"
  fi
  if [[ $platformunsupported == "false" ]]; then
    cd $REDIS_HOME && tar xzf $REDIS_ZIPNAME
    if [[ ! -d $REDIS_VERSION ]]; then
      echo "Corrupted redis zip. $REDIS_VERSION not found."
      exit
    fi
    cd $REDIS_VERSION
    make 32bit
  fi
else
  echo "Unsupported platform. Curently only Apple OS X and Linux systems (RedHat, CentOS, Ubuntu) are supported."
  platformunsupported="true"
fi
if [[ $platformunsupported == "false" ]]; then
  cp src/redis-server $REDIS_BIN 
  cp src/redis-sentinel $REDIS_BIN 
  cp src/redis-benchmark $REDIS_BIN 
  cp src/redis-cli $REDIS_BIN 
  cp src/redis-check-dump $REDIS_BIN 
  echo "installation script completed."
  echo "To start redis server, please run: ./redis-server"
fi

