[[building-spring-xd]]
== Building Spring XD

=== Instructions

Here are some useful steps to build and run Spring XD.

[WARNING]
====
Please ensure that you provide as a minimum _6GB of available RAM_ for a full build. The executed integration tests use several embedded services such as http://kafka.apache.org/[Apache Kafka], http://zookeeper.apache.org/[Apache ZooKeeper] and http://hadoop.apache.org/[Apache Hadoop] which contribute to the high resource usage.
====

To build all sub-projects and run tests for Spring XD (please note tests require a running http://redis.io/[Redis] instance):

----
./gradlew build
----

To build and bundle the distribution of Spring XD

----
./gradlew dist
----

The above gradle task creates spring-xd-<version>.zip binary distribution archive and spring-xd-<version>-docs.zip documentation archive files under 'build/distributions'. This will also create a 'build/dist/spring-xd' directory which is the expanded version of the binary distribution archive.

To just create the Spring XD expanded binary distribution directory

----
./gradlew copyInstall
----

The above gradle task creates the distribution directory under 'build/dist/spring-xd'.

Once the binary distribution directory is created, please refer to link:https://github.com/SpringSource/spring-xd/wiki/Getting-Started[Getting Started] on how to run Spring XD.

To create the reference docs

----
./gradlew reference
----

=== IDE support

If you would like to work with the Spring XD code in your IDE, please use the following project generation depending on the IDE you use:

For Eclipse/Spring Tool Suite

----
./gradlew eclipse
----

For IntelliJ IDEA
----
./gradlew idea
----
