#!/usr/bin/env bash

# @author Liujiong
# @since 1.0

##############################################################################
##
##  install-zookeeper script
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"ZOOKEEPER
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >&-
APP_HOME="`pwd -P`"
cd "$SAVED" >&-

ZOOKEEPER_VERSION=zookeeper-3.4.6
ZOOKEEPER_ZIP_NAME="$ZOOKEEPER_VERSION.tar.gz"
ZOOKEEPER_HOME=$APP_HOME
ZOOKEEPER_ZIP_FOLDER="$ZOOKEEPER_HOME/dist"
ZOOKEEPER_ZIP_PATH="$ZOOKEEPER_HOME/dist/$ZOOKEEPER_ZIP_NAME"
ZOOKEEPER_BIN="$ZOOKEEPER_HOME/bin"

if [[ ! -d $ZOOKEEPER_ZIP_FOLDER ]]; then
  mkdir -p $ZOOKEEPER_ZIP_FOLDER
fi

if [[ ! -f $ZOOKEEPER_ZIP_PATH ]]; then
  wget -P $ZOOKEEPER_ZIP_FOLDER wget http://apache.mirrors.pair.com/zookeeper/$ZOOKEEPER_VERSION/$ZOOKEEPER_ZIP_NAME
fi
cd $ZOOKEEPER_HOME && tar xzf $ZOOKEEPER_ZIP_PATH
if [[ ! -d $ZOOKEEPER_VERSION ]]; then
  echo "Corrupted zookeeper zip. $ZOOKEEPER_VERSION not found."
  exit
fi
rsync -a $ZOOKEEPER_VERSION/* . 
rm -rf $ZOOKEEPER_VERSION
cd $ZOOKEEPER_HOME
 
echo "installation script completed."
echo "To start zookeeper server, generate zoo.cfg under conf, then run: $ZOOKEEPER_BIN/zkServer.sh start"


