CREATE TABLE XD_JOB_REGISTRY (
JOB_NAME VARCHAR2(100) NOT NULL,
IS_INCREMENTABLE VARCHAR2(10) NOT NULL,
IS_RESTARTABLE VARCHAR2(10) NOT NULL
);
CREATE TABLE XD_JOB_REGISTRY_STEP_NAMES (
JOB_NAME VARCHAR2(100) NOT NULL,
STEP_NAME VARCHAR2(250) NOT NULL
);
