CREATE TABLE JOB_REGISTRY_NAMES (
        JOB_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE JOB_REGISTRY_INCREMENTABLES (
		JOB_NAME VARCHAR(100) NOT NULL,
		IS_INCREMENTABLE VARCHAR(10) NOT NULL
);
CREATE TABLE JOB_REGISTRY_RESTARTABLES (
		JOB_NAME VARCHAR(100) NOT NULL,
		IS_RESTARTABLE VARCHAR(10) NOT NULL
);
CREATE TABLE JOB_REGISTRY_STEP_NAMES (
		JOB_NAME VARCHAR(100) NOT NULL,
		STEP_NAME VARCHAR(250) NOT NULL
);
