#!/bin/sh

SQLITE_DIR=~/.m2/repository/org/xerial/sqlite-jdbc/3.7.2
SQLITE_JAR="$SQLITE_DIR/sqlite-jdbc-3.7.2.jar"

if [[ ! -f $SQLITE_JAR ]]
then
  mkdir -p "$SQLITE_DIR"
  curl http://central.maven.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar > $SQLITE_JAR
fi

cp $SQLITE_JAR ${XD_HOME:?}/lib

