#!/bin/bash

. xdapi
#If this the first time you are running this script, please run the install_sqlite_jar and restart the XD Server
PWD=`pwd`
TEST_DIR='/tmp/xdtest/jdbc'
DB_FILE="$TEST_DIR/jdbc.db"

if [[ ! -f $XD_HOME/lib/sqlite-jdbc-3.7.2.jar ]]
then
  echo 'sqlite jar is missing from XD_HOME/lib. Skipping JDBC tests'
  exit 0
fi

wait_for_server

rm -R $TEST_DIR &> /dev/null

mkdir -p $TEST_DIR
set -e
echo -e "\n\n Test 1. tail | jdbc stream with pre-initialized database"

sqlite3 $DB_FILE 'create table blah (col1 varchar, col2 varchar, col3 varchar)'

create_stream jdbc1 "tail --lines=10 --name=$TEST_DIR/jdbc1.data --fileDelay=1000 | jdbc --driverClass=org.sqlite.JDBC --username='' --password='' --url=jdbc:sqlite:$DB_FILE --initializeDatabase=false --columns=col1,col2,col3 --tableName=blah"

# Add some data to the file
echo '{"col1":"x", "col2":"y", "col3":"z"}' >> $TEST_DIR/jdbc1.data
sleep 3
rows=`sqlite3 $DB_FILE 'select count(*) from blah'`
destroy_stream jdbc1
rm $TEST_DIR/jdbc1.data

echo "Checking row count in database table matches import from tail file..."
assert_equals 1 $rows
col1=`sqlite3 $DB_FILE 'select col1 from blah'`
assert_equals 'x' $col1

echo -e "\n\n Test 2. tail | jdbc stream with db initialization"

create_stream jdbc2 "tail --lines=10 --name=$TEST_DIR/jdbc2.data --fileDelay=1000 | jdbc --driverClass=org.sqlite.JDBC --username='' --password='' --url=jdbc:sqlite:$DB_FILE --initializeDatabase=true"

echo "blahblah" >> $TEST_DIR/jdbc2.data
sleep 3
destroy_stream jdbc2
rm $TEST_DIR/jdbc2.data

echo "Checking row count in database table matches import from tail file..."
rows=`sqlite3 $DB_FILE 'select count(*) from jdbc2'`
assert_equals 1 $rows
payload=`sqlite3 $DB_FILE 'select payload from jdbc2'`
assert_equals 'blahblah' $payload

echo -e "\n\n Test 3. Load single CSV file using filejdbc job with defaults\n"

create_job csvjdbcjob0 "filejdbc --driverClass=org.sqlite.JDBC --url=jdbc:sqlite:$DB_FILE --names=col1,col2,col3 --resources=file://$PWD/csv/data.csv --initializeDatabase=true"
launch_job csvjdbcjob0
sleep 5
rows=`sqlite3 $DB_FILE 'select count(*) from csvjdbcjob0'`
destroy_job csvjdbcjob0
echo "Checking row count in database table matches import from file..."
assert_equals 292 $rows

echo -e "\n\n Test 4. Load multiple CSV files using filejdbc jobs with table name specified\n"

create_job csvjdbcjob1 "filejdbc --driverClass=org.sqlite.JDBC --url=jdbc:sqlite:$DB_FILE --names=col1,col2,col3 --resources=file://$PWD/csv/data.csv --tableName=JOB_TABLE --initializeDatabase=true"
launch_job csvjdbcjob1
sleep 5
destroy_job csvjdbcjob1
create_job csvjdbcjob2 "filejdbc --driverClass=org.sqlite.JDBC --url=jdbc:sqlite:$DB_FILE --names=col1,col2,col3 --resources=file://$PWD/csv/data.csv --tableName=JOB_TABLE --initializeDatabase=false"
launch_job csvjdbcjob2
sleep 5
destroy_job csvjdbcjob2
rows=`sqlite3 $DB_FILE 'select count(*) from JOB_TABLE'`
echo "Checking row count in database table matches import from file..."
assert_equals 584 $rows

echo -e '\nAll good :-)'
