#!/bin/bash

# Setting up for the test:
# We need to update activemq so it will not conflict with RabbitMQ running on the same machine.
# Once you have installed activemq,  edit the {activemq.home.dir}/data/activemq.xml file.
# 1) Remove the following lines:             
#     a) <transportConnector name="amqp" uri="amqp://0.0.0.0:5679?maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600"/>
#     b) <transportConnector name="mqtt" uri="mqtt://0.0.0.0:1889?maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600"/>
# 2) change the stomp port from 61613 to another port.   i.e. 62623
#

. xdapi

TEST_DIR=/tmp/xdtest/basic

wait_for_server

rm -R $TEST_DIR &> /dev/null
set -e

echo -e '*** Test 1. jms | file stream\n'

create_stream 'jmsSourceTest' 'jms | file --dir=/tmp/xdtest/basic/' 'false'
list_streams
deploy_stream 'jmsSourceTest'


jms_post_data_and_check_result() {
  curl -u admin:admin -d "body=jmsmessage" http://127.0.0.1:8161/api/message/jmsSourceTest?type=queue
  sleep 1
  result=`cat $TEST_DIR/jmsSourceTest.out`

  if [[ $result != 'jmsmessage' ]]
  then
    echo -e "\nPosted jms data ($result) does not match file sink contents"
    exit 1
  fi  
}


# Run, undeploy, redeploy and run again

sleep 5
jms_post_data_and_check_result

undeploy_stream 'jmsSourceTest'

destroy_stream 'jmsSourceTest'

echo -e '\nAll Good :-)\n'
