#!/bin/bash

. xdapi

TEST_DIR=/tmp/xdtest/basic

wait_for_server

rm -R $TEST_DIR &> /dev/null
set -e

echo -e '*** Test 1. mqtt | file stream\n'

create_stream 'mqttSourceTest' 'mqtt | file --dir=/tmp/xdtest/basic' 'false'
deploy_stream 'mqttSourceTest'

mqtt_post_data_and_check_result() {
  curl -X POST -i -u guest:guest -H "Content-Type: application/json" -d '{"properties":{},"routing_key":"xd.mqtt.test","payload":"test mqtt body","payload_encoding":"string"}' http://127.0.0.1:15672/api/exchanges/%2F/amq.topic/publish
  sleep 1
    result=`cat $TEST_DIR/mqttSourceTest.out`

  if [[ $result != 'test mqtt body' ]]
  then
    echo -e "\nPosted mqtt data ($result) does not match file sink contents"
    exit 1
  fi 
}


# Run, undeploy, redeploy and run again

mqtt_post_data_and_check_result

undeploy_stream 'mqttSourceTest'

destroy_stream 'mqttSourceTest'

echo -e '\nAll Good :-)\n'
